name: DAP
favicon: null
layout_spectrum: 0.7856430986430496
typography_spectrum: 0.08444738062098622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7079117959365249
  lightness: 0.4782749470323324
  saturation: 0.429622292984277
  rhythmicContrast: 0.02163002430461347
purpose: []
